### ISSUE TITLE
Not an editor command: LanguageClientStart

### ISSUE THREAD

**Issue by fantiq** [roxma/LanguageServer-php-neovim#1]
`neovim 1.7 `   and `centos 6.8`

this is my file `init.vim`

```
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/nvim-completion-manager'
Plug 'roxma/LanguageServer-php-neovim', {'do': 'composer install && composer run-script parse-stubs'}

autocmd FileType php LanguageClientStart
```

when i open the php file i get this error message:
```
Error detected while processing FileType Auto commands for "php":                                                                                                                                                    
E492: Not an editor command: LanguageClientStart
```

how to fix?
and thanks for your work :100:

**Comment by roxma** [comment]
Hi, you need to report an issue to [LanguageClient](https://github.com/autozimu/LanguageClient-neovim/issues/36)

**Comment by fantiq** [comment]
@roxma  thanks for your reply!
yes it is LanguageClient:
first  neovim need py3 support,then u should execute the following command `in shell`
```
nvim +PlugInstall +UpdateRemotePlugins +qa
```

when i reopen the neovim  it works well !
by the way , can this plugin support `goto definition` ?

**Comment by roxma** [comment]
Yes it support goto definition, read the [quick start](https://github.com/autozimu/LanguageClient-neovim#quick-start) section of LanguageClient
