### ISSUE TITLE
No language server command for for type: php

### ISSUE THREAD

**Issue by joereynolds** [roxma/LanguageServer-php-neovim#9]
With the configuration below, if I enter any php file and type `:LanguageClientStart`, I get 

```
No language server command for for type: php
```

```
   Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

  Plug 'roxma/LanguageServer-php-neovim',  {'do': 'composer install && composer run-script parse-stubs'}
```

**Comment by 0styx0** [comment]
Same. Is there supposed to be something to add to the `LanguageClient_serverCommands` object?

**Comment by hiqsol** [comment]
Have same problem.
I had this plugin working previously on other computer.

**Comment by 0styx0** [comment]
@hiqsol, @joereynolds randomly tried it again today and working for me now

**Comment by joereynolds** [comment]
@david-me ,

Seems to work now too, this was my setup with vim-plug

```
    Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

    Plug 'roxma/LanguageServer-php-neovim',  {'do': 'composer install && composer run-script parse-stubs'}

```

**Comment by hiqsol** [comment]
For me it worked to completely reset plug: remove whole `.vim/plugged` folder and reinstall with PlugUpdate.
